// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoBurger_MVC_API_MAUI.Data;

#nullable disable

namespace ProyectoBurger_MVC_API_MAUI.Migrations
{
    [DbContext(typeof(ProyectoBurger_MVC_API_MAUIContext))]
    [Migration("20240530232109_Burger_JDS")]
    partial class Burger_JDS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoBurger_MVC_API_MAUI.Models.Burger_JDS", b =>
                {
                    b.Property<int>("BurgerId_JDS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BurgerId_JDS"));

                    b.Property<string>("Name_JDS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio_JDS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("WithCheese_JDS")
                        .HasColumnType("bit");

                    b.HasKey("BurgerId_JDS");

                    b.ToTable("Burger_JDS");
                });

            modelBuilder.Entity("ProyectoBurger_MVC_API_MAUI.Models.Promo_JDS", b =>
                {
                    b.Property<int>("PromoId_JDS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId_JDS"));

                    b.Property<int>("BurgerId_JDS")
                        .HasColumnType("int");

                    b.Property<int?>("Burger_JDSBurgerId_JDS")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion_JDS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPromo_JDS")
                        .HasColumnType("datetime2");

                    b.HasKey("PromoId_JDS");

                    b.HasIndex("Burger_JDSBurgerId_JDS");

                    b.ToTable("Promo_JDS");
                });

            modelBuilder.Entity("ProyectoBurger_MVC_API_MAUI.Models.Promo_JDS", b =>
                {
                    b.HasOne("ProyectoBurger_MVC_API_MAUI.Models.Burger_JDS", "Burger_JDS")
                        .WithMany("Promo_JDS")
                        .HasForeignKey("Burger_JDSBurgerId_JDS");

                    b.Navigation("Burger_JDS");
                });

            modelBuilder.Entity("ProyectoBurger_MVC_API_MAUI.Models.Burger_JDS", b =>
                {
                    b.Navigation("Promo_JDS");
                });
#pragma warning restore 612, 618
        }
    }
}
